aggregator:
  group-timeout: '15000' # 30 minutes

# Override logging configuration
logging:
  level.root: INFO
  level.org.springframework: INFO
  level.org.apache.kafka: WARN
  level.com.soufianeroui: DEBUG
