management:
  endpoints.web.exposure.include:
    - prometheus
    - metrics
  metrics:
    enable:
      tomcat: false
      http: false
      jvm: false
      logback: false
      process: false
      system: false
      application: false
      disk: false
      executor: false

