server:
  port: 8080
  servlet:
    context-path: /
    session:
      persistent: false
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/xml
  # See https://docs.spring.io/spring-boot/docs/current/reference/html/web.html#web.graceful-shutdown
  shutdown: graceful

spring:
  main:
    banner-mode: log

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC

  lifecycle:
    timeout-per-shutdown-phase: 30s

  task:
    scheduling:
      pool:
        size: 10
    execution:
      thread-name-prefix: event-supplier-

  cloud:
    stream:
      bindings:
        outputChannel-in-0:
          consumer:
            max-attempts: 0

aggregator:
  correlation: headers[T(com.soufianeroui.tutorials.scs.aggregation.event.aggregator.constants.EventsAggregatorConstants).EVENT_GROUP_ID_MESSAGE_HEADER]
  release: messages.size == T(com.soufianeroui.tutorials.scs.aggregation.event.aggregator.constants.EventsAggregatorConstants).EVENT_GROUP_SIZE
  messageStoreType: simple
  group-timeout: '1000' # 30 minutes

management:
  endpoints.web.exposure.include:
    - health
    - bindings
  endpoint.health.probes.enabled: true
  health:
    livenessState.enabled: true
    readinessState.enabled: true

logging:
  level.root: INFO
  level.org.springframework.boot: INFO
  level.com.soufianeroui: INFO